export const customTheme = {
  default: {
    colors: {
      brand: "white",
      brandAccent: "#eaeaea",
      brandButtonText: "black",
      defaultButtonBackground: "white",
      defaultButtonBackgroundHover: "#eaeaea",
      defaultButtonBorder: "black",
      defaultButtonText: "black",
      dividerBackground: "#eaeaea",
      inputBackground: "transparent",
      inputBorder: "lightgray",
      inputBorderHover: "gray",
      inputBorderFocus: "gray",
      inputText: "black",
      inputLabelText: "black",
      inputPlaceholder: "darkgray",
      messageText: "gray",
      messageTextDanger: "red",
      anchorTextColor: "black",
      anchorTextHoverColor: "black",
    },
    space: {
      spaceSmall: "4px",
      spaceMedium: "8px",
      spaceLarge: "16px",
      labelBottomMargin: "8px",
      anchorBottomMargin: "4px",
      emailInputSpacing: "4px",
      socialAuthSpacing: "4px",
      buttonPadding: "10px 15px",
      inputPadding: "10px 15px",
    },
    fontSizes: {
      baseBodySize: "12px",
      baseInputSize: "13px",
      baseLabelSize: "13px",
      baseButtonSize: "13px",
    },
    fonts: {
      bodyFontFamily: `Inter, sans-serif`,
      buttonFontFamily: `Inter, sans-serif`,
      inputFontFamily: `Inter, sans-serif`,
      labelFontFamily: `Inter, sans-serif`,
    },
    fontWeights: {},
    borderWidths: {
      buttonBorderWidth: "1px",
      inputBorderWidth: "1px",
    },
    radii: {
      borderRadiusButton: "10px",
      buttonBorderRadius: "5px",
      inputBorderRadius: "10px",
    },
  },
};
